icap_notification:
    resource: "@IcapNotificationBundle/Controller/"
    type:     annotation
    prefix: /
icap_notification_api:
    resource: "@IcapNotificationBundle/Controller/ApiController.php"
    type: rest
    prefix: api
    defaults: {_format: json}
    options:
        expose: true